/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "apps.dashboard": [],
    "apps.permissions.index": [],
    "apps.roles.index": [],
    "apps.roles.create": [],
    "apps.roles.store": [],
    "apps.roles.show": [
        {
            "name": "role"
        }
    ],
    "apps.roles.edit": [
        {
            "name": "role"
        }
    ],
    "apps.roles.update": [
        {
            "name": "role"
        }
    ],
    "apps.roles.destroy": [
        {
            "name": "role"
        }
    ]
}
}
export {};
